# SPDX-FileCopyrightText: (C) 2021 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

PERF_TESTS_PATH=tests/perf_tests
define perf-recipe =
	$(eval BASE_CMD := $1)
	$(eval BASE_CMD := $(BASE_CMD))
	$(eval TEST_SCRIPT := $(BASE_CMD))
	$(eval LOGFILE=$(TEST_DATA)/perf/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
	  ; echo RUNNING TEST $@ \
	  ; cd .. \
	  ; mkdir -p $(shell dirname $(LOGFILE)) \
	  ; env IMAGE=$(BASE_IMAGE):$(VERSION) $(PERF_TESTS_PATH)/$(TEST_SCRIPT) 2>&1 | tee -i $(LOGFILE) \
	  ; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
	  ; echo END TEST $@
endef

performance_tests:
	$(MAKE) -Otarget -j 1 _performance_tests SUPASS=$(SUPASS) -k

# TODO: re-enable with DLS scene-performance
_performance_tests: \
  inference-performance \
  geometry-conformance \

geometry-conformance: \
  point-conformance \
  line-conformance \

# Recipes below must be in alphabetical order

inference-performance: # NEX-T10412
	$(call perf-recipe, tc_inference_performance.sh)

scene-performance: # NEX-T10414
	$(call perf-recipe, tc_scene_performance.sh)

scene-performance-full: # NEX-T10488
	# 2 Cameras at 10fps, 2 models
	$(eval TARGET_RATE ?= 40)
	$(call perf-recipe, tc_scene_performance_full --target $(TARGET_RATE))

# Compare C++ geometry implementation
# vs original python implementation.
point-conformance:
	$(eval LOGDIR=$(TEST_DATA)/infra)
	$(eval LOGFILE=$(LOGDIR)/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
          ; echo RUNNING TEST $@ \
          ; cd .. \
          ; mkdir -p $(LOGDIR) \
          ; tools/scenescape-start --image $(IMAGE)-manager-test $(PERF_TESTS_PATH)/tc_geometry_point.py  | tee -ia $(LOGFILE) \
          ; echo END TEST $@

line-conformance:
	$(eval LOGDIR=$(TEST_DATA)/infra)
	$(eval LOGFILE=$(LOGDIR)/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
          ; echo RUNNING TEST $@ \
          ; cd .. \
          ; mkdir -p $(LOGDIR) \
          ; tools/scenescape-start --image $(IMAGE)-manager-test $(PERF_TESTS_PATH)/tc_geometry_line.py | tee -ia $(LOGFILE) \
          ; echo END TEST $@
