---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

misconfigurations:
  # Helm chart
  - id: AVD-KSV-0005
    paths:
      - "kubernetes/scenescape-chart/templates/web-dep.yaml"
    statement: Current implementation requires admin capabilities
  - id: AVD-KSV-0014
    paths:
      - "kubernetes/scenescape-chart/templates/camcalibration-dep.yaml"
      - "kubernetes/scenescape-chart/templates/pgserver-dep.yaml"
      - "kubernetes/scenescape-chart/templates/queuing-dep.yaml"
      - "kubernetes/scenescape-chart/templates/retail-dep.yaml"
      - "kubernetes/scenescape-chart/templates/vdms-dep.yaml"
      - "kubernetes/scenescape-chart/templates/web-dep.yaml"
      - "kubernetes/scenescape-chart/templates/kubeclient-dep.yaml"
    statement: Current implementation requires these containers to write to filesystem
  - id: AVD-KSV-0017
    paths:
      - "kubernetes/scenescape-chart/templates/web-dep.yaml"
    statement: Current implementation requires privileged container
